import test from 'node:test'
import assert from 'node:assert/strict'
import { buildSyncedObservation, parseArgs } from '../scripts/sync-github-observations.mjs'

test('sync defaults to dry-run and requires explicit write', () => {
  assert.equal(parseArgs([]).write, false)
  assert.equal(parseArgs(['--write']).write, true)
  assert.throws(() => parseArgs(['--limit', '101']), /1 to 100/)
  assert.throws(() => parseArgs(['--unexpected']), /Unknown argument/)
})

test('first review ignores earlier issue comments and attribution remains auditable', () => {
  const observation = buildSyncedObservation({
    number: 1,
    title: 'plain title',
    body: 'generated by copilot',
    author: { login: 'example-user', is_bot: false },
    createdAt: '2026-01-01T00:00:00Z',
    comments: [{ createdAt: '2026-01-01T01:00:00Z', author: { login: 'reviewer' } }],
    reviews: [{ submittedAt: '2026-01-01T02:00:00Z', author: { login: 'reviewer' } }],
    labels: [], files: [], additions: 1, deletions: 0, state: 'OPEN', url: 'https://example.test/pr/1'
  }, 'owner/repo')

  assert.equal(observation.firstCommentedAt, '2026-01-01T01:00:00Z')
  assert.equal(observation.firstReviewedAt, '2026-01-01T02:00:00Z')
  assert.deepEqual(observation.attributionSignals, ['body-pattern'])
})
