const fs = require('fs')
const path = require('path')

const defaultObservationPath = path.join(process.cwd(), 'docs', 'pr-observations.json')

function readObservations(filePath = defaultObservationPath) {
  if (!fs.existsSync(filePath)) {
    return []
  }

  const raw = fs.readFileSync(filePath, 'utf8')
  const parsed = JSON.parse(raw)

  if (!Array.isArray(parsed)) {
    return []
  }

  return parsed
}

function isAiAuthored(observation) {
  if (!observation || typeof observation !== 'object') {
    return false
  }

  if (typeof observation.aiAuthored === 'boolean') {
    return observation.aiAuthored
  }

  const author = String(observation.author || '').toLowerCase()
  const title = String(observation.title || '').toLowerCase()
  const body = String(observation.body || '').toLowerCase()
  const labels = Array.isArray(observation.labels) ? observation.labels.join(' ').toLowerCase() : ''

  return [
    author.includes('copilot'),
    author.includes('bot'),
    author.includes('gpt'),
    author.includes('claude'),
    title.includes('ai'),
    title.includes('automated'),
    body.includes('generated by'),
    body.includes('co-authored-by'),
    labels.includes('ai')
  ].some(Boolean)
}

function asDate(value) {
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? null : date
}

function daysBetween(left, right) {
  return Math.floor((left.getTime() - right.getTime()) / (1000 * 60 * 60 * 24))
}

function sum(items, selector) {
  return items.reduce((total, item) => total + selector(item), 0)
}

function average(items, selector) {
  if (!items.length) {
    return null
  }

  return Number((sum(items, selector) / items.length).toFixed(2))
}

function pickRecent(items, now, days) {
  return items.filter((item) => {
    const openedAt = asDate(item.openedAt || item.createdAt)
    return openedAt && daysBetween(now, openedAt) <= days
  })
}

function buildSnapshot(options = {}) {
  const now = asDate(options.now) || new Date()
  const observations = options.observations || readObservations(options.filePath)
  const normalized = observations.map((observation) => ({
    ...observation,
    inferredAiAuthored: isAiAuthored(observation)
  }))

  const aiObservations = normalized.filter((observation) => observation.inferredAiAuthored)
  const humanObservations = normalized.filter((observation) => !observation.inferredAiAuthored)
  const recentAi = pickRecent(aiObservations, now, 7)
  const recentMergedAi = aiObservations.filter((observation) => {
    if (observation.state !== 'merged') {
      return false
    }

    const mergedAt = asDate(observation.mergedAt)
    return mergedAt && daysBetween(now, mergedAt) <= 30
  })
  const recentClosed = normalized.filter((observation) => {
    const closedAt = asDate(observation.closedAt || observation.mergedAt)
    return closedAt && daysBetween(now, closedAt) <= 14
  })
  const scored = normalized.filter((observation) => typeof observation.reviewEntertainmentScore === 'number')

  const aiPrVelocity = recentAi.length
  const slopDensity = humanObservations.length
    ? Number((aiObservations.length / humanObservations.length).toFixed(2))
    : aiObservations.length
  const churnContribution = sum(recentClosed, (observation) => Number(observation.revertedLines || 0))
  const engagementDepth = sum(recentMergedAi, (observation) => Number(observation.followUpPrsTriggered || 0))
  const reviewEntertainmentValue = average(scored, (observation) => observation.reviewEntertainmentScore)

  return {
    generatedAt: now.toISOString(),
    observationCount: normalized.length,
    aiObservationCount: aiObservations.length,
    humanObservationCount: humanObservations.length,
    aiPrVelocity,
    slopDensity,
    churnContribution,
    engagementDepth,
    reviewEntertainmentValue,
    recentAiPrNumbers: recentAi.map((observation) => observation.number),
    topFollowUpChains: aiObservations
      .filter((observation) => Number(observation.followUpPrsTriggered || 0) > 0)
      .sort((left, right) => Number(right.followUpPrsTriggered || 0) - Number(left.followUpPrsTriggered || 0))
      .slice(0, 5)
      .map((observation) => ({
        number: observation.number,
        title: observation.title,
        followUpPrsTriggered: Number(observation.followUpPrsTriggered || 0)
      }))
  }
}

module.exports = {
  buildSnapshot,
  defaultObservationPath,
  isAiAuthored,
  readObservations
}
