const fs = require('fs')
const path = require('path')
const { createCache } = require('./cache')
const { normalizeObservation } = require('./pr-normalize')
const { summarizeReviewEnergy } = require('./review-score')
const { buildCurationNotes } = require('./triage')

const defaultObservationPath = path.join(process.cwd(), 'docs', 'pr-observations.json')
const metricsCache = createCache()

function readObservations(filePath = defaultObservationPath) {
  if (!fs.existsSync(filePath)) {
    return []
  }

  const raw = fs.readFileSync(filePath, 'utf8')
  const parsed = JSON.parse(raw)

  if (!Array.isArray(parsed)) {
    return []
  }

  return parsed
}

function isAiAuthored(observation) {
  if (!observation || typeof observation !== 'object') {
    return false
  }

  if (typeof observation.aiAuthored === 'boolean') {
    return observation.aiAuthored
  }

  const author = String(observation.author || '').toLowerCase()
  const title = String(observation.title || '').toLowerCase()
  const body = String(observation.body || '').toLowerCase()
  const labels = Array.isArray(observation.labels) ? observation.labels.join(' ').toLowerCase() : ''

  return [
    author.includes('copilot'),
    author.includes('bot'),
    author.includes('gpt'),
    author.includes('claude'),
    author.includes('-ai'),
    /\bautomated\b|\bcopilot\b|\bclaude\b|\bchatgpt\b|\bgpt\b|\bdevin\b|\bcursor\b/.test(title),
    body.includes('generated by'),
    body.includes('co-authored-by'),
    labels.includes('ai')
  ].some(Boolean)
}

function asDate(value) {
  if (value === null || value === undefined || value === '') {
    return null
  }

  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? null : date
}

function daysBetween(left, right) {
  return Math.floor((left.getTime() - right.getTime()) / (1000 * 60 * 60 * 24))
}

function sum(items, selector) {
  return items.reduce((total, item) => total + selector(item), 0)
}

function countBy(items, selector) {
  return items.reduce((counts, item) => {
    const key = selector(item) || 'unknown'
    counts[key] = (counts[key] || 0) + 1
    return counts
  }, {})
}

function countByMany(items, selector) {
  return items.reduce((counts, item) => {
    const values = Array.isArray(selector(item)) ? selector(item) : []

    values.forEach((value) => {
      const key = value || 'unknown'
      counts[key] = (counts[key] || 0) + 1
    })

    return counts
  }, {})
}

function average(items, selector) {
  if (!items.length) {
    return null
  }

  return Number((sum(items, selector) / items.length).toFixed(2))
}

function ratio(left, right) {
  if (!right) {
    return left ? Number(left.toFixed ? left.toFixed(2) : left) : 0
  }

  return Number((left / right).toFixed(2))
}

function pickRecent(items, now, days) {
  return items.filter((item) => {
    const openedAt = asDate(item.openedAt || item.createdAt)
    return openedAt && daysBetween(now, openedAt) <= days
  })
}

function collectAuthorCounts(observations) {
  return observations.reduce((counts, observation) => {
    const author = observation.author || 'unknown'
    counts[author] = (counts[author] || 0) + 1
    return counts
  }, {})
}

function sortedEntries(counts, limit = 5) {
  return Object.entries(counts)
    .sort((left, right) => right[1] - left[1])
    .slice(0, limit)
    .map(([key, count]) => ({ key, count }))
}

function buildSurfaceAttractionBreakdown(observations) {
  const counts = {}

  observations.forEach((observation) => {
    const areas = Array.isArray(observation.changedAreas) ? observation.changedAreas : []

    areas.forEach((area) => {
      const key = area || 'unknown'

      if (!counts[key]) {
        counts[key] = {
          key,
          aiCount: 0,
          humanCount: 0,
          totalCount: 0,
          attractionIndex: 0,
          aiShare: 0
        }
      }

      counts[key].totalCount += 1

      if (observation.inferredAiAuthored) {
        counts[key].aiCount += 1
      } else {
        counts[key].humanCount += 1
      }
    })
  })

  return Object.values(counts)
    .map((entry) => ({
      ...entry,
      attractionIndex: Number((entry.aiCount / Math.max(1, entry.humanCount)).toFixed(2)),
      aiShare: Number((entry.aiCount / Math.max(1, entry.totalCount)).toFixed(2))
    }))
    .sort((left, right) => {
      if (right.attractionIndex !== left.attractionIndex) {
        return right.attractionIndex - left.attractionIndex
      }

      return right.totalCount - left.totalCount
    })
}

function buildAgentFamilyStats(aiObservations) {
  const counts = countBy(aiObservations, (observation) => observation.agentFamily)
  const families = Object.entries(counts).map(([family, count]) => ({
    family,
    count,
    repeatContributor: count > 1
  }))
  const repeatFamilies = families.filter((item) => item.repeatContributor)
  const firstTimeFamilies = families.filter((item) => !item.repeatContributor)

  return {
    families,
    repeatFamilies,
    firstTimeFamilies,
    repeatAgentFamilyRate: ratio(repeatFamilies.length, families.length),
    firstTimeAgentFamilyRatio: ratio(firstTimeFamilies.length, families.length)
  }
}

function buildChainStarterSummary(aiObservations) {
  return aiObservations
    .map((observation) => {
      const followUps = Number(observation.followUpPrsTriggered || 0)
      const potential = Number(observation.followOnPotential || 0)
      const speculativeBonus = observation.speculativeFix ? 1 : 0

      return {
        number: observation.number,
        title: observation.title,
        changedAreas: observation.changedAreas || [],
        followUpPrsTriggered: followUps,
        followOnPotential: potential,
        chainStarterIndex: Number((followUps + (potential * 0.5) + speculativeBonus).toFixed(2))
      }
    })
    .filter((observation) => observation.chainStarterIndex > 0)
    .sort((left, right) => right.chainStarterIndex - left.chainStarterIndex)
    .slice(0, 5)
}

function buildRawSnapshot(options = {}) {
  const now = asDate(options.now) || new Date()
  const observations = (options.observations || readObservations(options.filePath))
    .map((observation) => normalizeObservation(observation, { isAiAuthored, asDate }))

  const aiObservations = observations.filter((observation) => observation.inferredAiAuthored)
  const humanObservations = observations.filter((observation) => !observation.inferredAiAuthored)
  const recentAi = pickRecent(aiObservations, now, 7)
  const recentMergedAi = aiObservations.filter((observation) => {
    if (observation.state !== 'merged') {
      return false
    }

    const mergedAt = asDate(observation.mergedAt)
    return mergedAt && daysBetween(now, mergedAt) <= 30
  })
  const recentClosed = observations.filter((observation) => {
    const closedAt = asDate(observation.closedAt || observation.mergedAt)
    return closedAt && daysBetween(now, closedAt) <= 14
  })
  const scored = observations.filter((observation) => typeof observation.reviewEntertainmentScore === 'number')
  const speculative = observations.filter((observation) => observation.speculativeFix)
  const promptScored = observations.filter((observation) => typeof observation.promptComplianceScore === 'number')
  const followOnScored = observations.filter((observation) => typeof observation.followOnPotential === 'number')
  const reviewTimed = observations.filter((observation) => typeof observation.timeToFirstReviewHours === 'number')
  const mergeTimed = observations.filter((observation) => typeof observation.timeToMergeHours === 'number')
  const linkedIssueCount = sum(observations, (observation) => observation.linkedIssues.length)
  const changedFileCount = sum(observations, (observation) => observation.changedFiles.length)
  const changedAreaBreakdown = countByMany(observations, (observation) => observation.changedAreas)
  const authorTypeBreakdown = countBy(observations, (observation) => observation.authorType)
  const agentFamilyBreakdown = countBy(aiObservations, (observation) => observation.agentFamily)
  const repeatBotAuthors = Object.entries(collectAuthorCounts(aiObservations))
    .filter(([, count]) => count > 1)
    .map(([author]) => author)
    .sort()
  const surfaceAttractionBreakdown = buildSurfaceAttractionBreakdown(observations)
  const agentFamilyStats = buildAgentFamilyStats(aiObservations)
  const chainStarterSummary = buildChainStarterSummary(aiObservations)
  const reviewEnergy = summarizeReviewEnergy(scored)
  const curation = buildCurationNotes(observations)

  return {
    generatedAt: now.toISOString(),
    rawObservationWindowDays: 30,
    observationCount: observations.length,
    aiObservationCount: aiObservations.length,
    humanObservationCount: humanObservations.length,
    aiPrVelocity: recentAi.length,
    slopDensity: ratio(aiObservations.length, humanObservations.length),
    churnContribution: sum(recentClosed, (observation) => Number(observation.revertedLines || 0)),
    engagementDepth: sum(recentMergedAi, (observation) => Number(observation.followUpPrsTriggered || 0)),
    reviewEntertainmentValue: average(scored, (observation) => observation.reviewEntertainmentScore),
    mergeOptimism: ratio(
      aiObservations.filter((observation) => observation.state === 'merged').length,
      aiObservations.length
    ),
    speculativeMaintenanceRatio: ratio(speculative.length, observations.length),
    botRecidivism: ratio(repeatBotAuthors.length, Object.keys(collectAuthorCounts(aiObservations)).length),
    promptComplianceDrift: promptScored.length
      ? Number((5 - average(promptScored, (observation) => observation.promptComplianceScore)).toFixed(2))
      : null,
    maintainerAmusementIndex: reviewEnergy.maintainerAmusementIndex,
    averageFollowOnPotential: average(followOnScored, (observation) => observation.followOnPotential),
    averageTimeToFirstReviewHours: average(reviewTimed, (observation) => observation.timeToFirstReviewHours),
    averageTimeToMergeHours: average(mergeTimed, (observation) => observation.timeToMergeHours),
    linkedIssueCount,
    changedFileCount,
    dependencyTouchedCount: observations.filter((observation) => observation.dependencyTouched).length,
    docsTouchedCount: observations.filter((observation) => observation.docsTouched).length,
    authTouchedCount: observations.filter((observation) => observation.authTouched).length,
    performanceTouchedCount: observations.filter((observation) => observation.performanceTouched).length,
    dependencyDramaRate: ratio(observations.filter((observation) => observation.dependencyTouched).length, observations.length),
    authAmbiguityYield: ratio(aiObservations.filter((observation) => observation.authTouched).length, observations.filter((observation) => observation.authTouched).length),
    surfaceAreaAttractionIndex: surfaceAttractionBreakdown.length ? surfaceAttractionBreakdown[0].attractionIndex : 0,
    repeatAgentFamilyRate: agentFamilyStats.repeatAgentFamilyRate,
    firstTimeAgentFamilyRatio: agentFamilyStats.firstTimeAgentFamilyRatio,
    recentAiPrNumbers: recentAi.map((observation) => observation.number),
    repeatBotAuthors,
    authorTypeBreakdown,
    agentFamilyBreakdown,
    changedAreaBreakdown,
    topTouchedAreas: sortedEntries(changedAreaBreakdown),
    topAgentFamilies: sortedEntries(agentFamilyBreakdown),
    repeatAgentFamilies: agentFamilyStats.repeatFamilies,
    firstTimeAgentFamilies: agentFamilyStats.firstTimeFamilies,
    surfaceAttractionBreakdown,
    topAttractedSurfaces: surfaceAttractionBreakdown.slice(0, 5),
    toneBreakdown: curation.toneBreakdown,
    triageMoodBreakdown: curation.triageMoodBreakdown,
    observations,
    topChainStarters: chainStarterSummary,
    topFollowUpChains: aiObservations
      .filter((observation) => Number(observation.followUpPrsTriggered || 0) > 0)
      .sort((left, right) => Number(right.followUpPrsTriggered || 0) - Number(left.followUpPrsTriggered || 0))
      .slice(0, 5)
      .map((observation) => ({
        number: observation.number,
        title: observation.title,
        followUpPrsTriggered: Number(observation.followUpPrsTriggered || 0)
      }))
  }
}

function buildSnapshot(options = {}) {
  const cacheKey = JSON.stringify({
    filePath: options.filePath || defaultObservationPath,
    now: options.now || '',
    inlineObservationCount: Array.isArray(options.observations) ? options.observations.length : null
  })
  const cached = metricsCache.get(cacheKey)

  if (cached) {
    return cached
  }

  const raw = buildRawSnapshot(options)
  const notes = buildCurationNotes(raw.observations)

  const curated = {
    generatedAt: raw.generatedAt,
    observationCount: raw.observationCount,
    aiObservationCount: raw.aiObservationCount,
    humanObservationCount: raw.humanObservationCount,
    aiPrVelocity: raw.aiPrVelocity,
    slopDensity: raw.slopDensity,
    churnContribution: raw.churnContribution,
    engagementDepth: raw.engagementDepth,
    reviewEntertainmentValue: raw.reviewEntertainmentValue,
    mergeOptimism: raw.mergeOptimism,
    speculativeMaintenanceRatio: raw.speculativeMaintenanceRatio,
    botRecidivism: raw.botRecidivism,
    promptComplianceDrift: raw.promptComplianceDrift,
    maintainerAmusementIndex: raw.maintainerAmusementIndex,
    averageFollowOnPotential: raw.averageFollowOnPotential,
    averageTimeToFirstReviewHours: raw.averageTimeToFirstReviewHours,
    averageTimeToMergeHours: raw.averageTimeToMergeHours,
    linkedIssueCount: raw.linkedIssueCount,
    changedFileCount: raw.changedFileCount,
    dependencyTouchedCount: raw.dependencyTouchedCount,
    docsTouchedCount: raw.docsTouchedCount,
    authTouchedCount: raw.authTouchedCount,
    performanceTouchedCount: raw.performanceTouchedCount,
    dependencyDramaRate: raw.dependencyDramaRate,
    authAmbiguityYield: raw.authAmbiguityYield,
    surfaceAreaAttractionIndex: raw.surfaceAreaAttractionIndex,
    repeatAgentFamilyRate: raw.repeatAgentFamilyRate,
    firstTimeAgentFamilyRatio: raw.firstTimeAgentFamilyRatio,
    recentAiPrNumbers: raw.recentAiPrNumbers,
    topFollowUpChains: raw.topFollowUpChains,
    topChainStarters: raw.topChainStarters,
    authorTypeBreakdown: raw.authorTypeBreakdown,
    agentFamilyBreakdown: raw.agentFamilyBreakdown,
    changedAreaBreakdown: raw.changedAreaBreakdown,
    topTouchedAreas: raw.topTouchedAreas,
    topAgentFamilies: raw.topAgentFamilies,
    repeatAgentFamilies: raw.repeatAgentFamilies,
    firstTimeAgentFamilies: raw.firstTimeAgentFamilies,
    surfaceAttractionBreakdown: raw.surfaceAttractionBreakdown,
    topAttractedSurfaces: raw.topAttractedSurfaces,
    curationNotes: notes.notes,
    hotSpots: notes.hotSpots,
    changedAreaBreakdownFromNotes: notes.changedAreaBreakdown,
    toneBreakdown: notes.toneBreakdown,
    triageMoodBreakdown: notes.triageMoodBreakdown
  }

  metricsCache.set(cacheKey, curated, 1500)
  return curated
}

function buildNarrativeReport(options = {}) {
  const raw = buildRawSnapshot(options)
  const curated = buildSnapshot(options)

  return [
    '# Weekly Observatory Report',
    '',
    `Generated: ${curated.generatedAt}`,
    '',
    '## Summary',
    '',
    `AI pull request velocity stayed at ${curated.aiPrVelocity} over the last 7 days while slop density landed at ${curated.slopDensity}.`,
    `Maintainers absorbed ${curated.churnContribution} reverted lines recently, with engagement depth sitting at ${curated.engagementDepth}.`,
    `Merge optimism is ${curated.mergeOptimism} and bot recidivism is ${curated.botRecidivism}.`,
    curated.topTouchedAreas.length
      ? `The busiest maintenance surface was ${curated.topTouchedAreas[0].key}, appearing ${curated.topTouchedAreas[0].count} times in the current sample.`
      : 'Surface-area tracking is still too thin to call a clear hotspot.',
    curated.topAttractedSurfaces.length
      ? `The most AI-attractive surface was ${curated.topAttractedSurfaces[0].key}, with an attraction index of ${curated.topAttractedSurfaces[0].attractionIndex}.`
      : 'AI-vs-human surface attraction is still too thin to rank.',
    '',
    '## Curation Notes',
    '',
    ...curated.curationNotes.map((note) => `- ${note}`),
    '',
    '## Contributor Shape',
    '',
    ...(curated.topAgentFamilies.length
      ? curated.topAgentFamilies.map((family) => `- ${family.key} showed up ${family.count} times in AI-authored observations`)
      : ['- No repeat agent families yet']),
    `- Repeat agent family rate is ${curated.repeatAgentFamilyRate} while first-time family ratio is ${curated.firstTimeAgentFamilyRatio}`,
    '',
    '## Surface Attraction',
    '',
    ...(curated.topAttractedSurfaces.length
      ? curated.topAttractedSurfaces.map((surface) => `- ${surface.key} drew ${surface.aiCount} AI observations and ${surface.humanCount} human observations (index ${surface.attractionIndex})`)
      : ['- No surface attraction data yet']),
    '',
    '## Hot Spots',
    '',
    ...(curated.hotSpots.length ? curated.hotSpots.map((spot) => `- ${spot}`) : ['- No obvious hot spots this round']),
    '',
    '## Chain Starters',
    '',
    ...(curated.topChainStarters.length
      ? curated.topChainStarters.map((chain) => `- PR #${chain.number} "${chain.title}" landed a chain starter index of ${chain.chainStarterIndex}`)
      : ['- No convincing chain starters yet']),
    '',
    '## Follow-up Chains',
    '',
    ...(raw.topFollowUpChains.length
      ? raw.topFollowUpChains.map((chain) => `- PR #${chain.number} "${chain.title}" spawned ${chain.followUpPrsTriggered} follow-up PRs`)
      : ['- No follow-up chains yet'])
  ].join('\n')
}

module.exports = {
  buildNarrativeReport,
  buildRawSnapshot,
  buildSnapshot,
  defaultObservationPath,
  isAiAuthored,
  readObservations
}
